# Generated by Django 4.2.16 on 2024-11-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIZZA_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.FileField(default='IMG/PRODUCT/PIZZA.png', upload_to='static/IMG/PRODUCT'),
        ),
    ]
