# Generated by Django 4.2.16 on 2024-11-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIZZA_APP', '0002_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.FileField(default='static/IMG/PRODUCT/PIZZA.png', upload_to='static/IMG/PRODUCT'),
        ),
    ]
