# Generated by Django 4.2.16 on 2024-11-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PIZZA_APP', '0003_alter_dish_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='dis',
            field=models.TextField(default='pizza'),
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.ManyToManyField(to='PIZZA_APP.category'),
        ),
    ]
