# Generated by Django 4.2.16 on 2024-10-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PR_7_APP', '0002_company_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='category',
        ),
    ]
