# Generated by Django 4.2.16 on 2024-10-29 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PR_7_APP', '0003_rename_company_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название блюда', max_length=100, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, help_text='Введите описание блюда', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите цену блюда', max_digits=6, verbose_name='Цена')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Введите категорию', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(help_text='Введите возраст человека', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Введите имя человека', max_length=100, verbose_name='Имя'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='PR_7_APP.category', verbose_name='Категория'),
        ),
    ]
