# Generated by Django 4.2.16 on 2024-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR_16_APP', '0002_person_user_remove_student_courses_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='ïmage',
            field=models.ImageField(default='/static/IMG.png', upload_to='', verbose_name='Изображение'),
        ),
    ]
