# Generated by Django 4.2.16 on 2024-11-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR_16_APP', '0003_alter_person_options_alter_person_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ïmage',
            field=models.ImageField(default='IMG.png', upload_to='', verbose_name='Изображение'),
        ),
    ]
