# Generated by Django 4.2.16 on 2024-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR_16_APP', '0004_alter_person_ïmage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='ïmage',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(default='IMG.png', upload_to='static', verbose_name='Изображение'),
        ),
    ]
