# Generated by Django 4.2.16 on 2024-11-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PR_16_APP', '0005_remove_person_ïmage_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(default='IMG.png', upload_to='static', verbose_name='Изображение'),
        ),
    ]
